import jsPDF from 'jspdf';

interface Banquet {
  id: string;
  name: string;
  city: string;
  capacity: number;
  basePrice: number;
}

interface QuoteData {
  clientName: string;
  eventDate: string;
  pricePerPlate: number;
  guests: number;
  rooms: number;
  notes: string;
}

export const generateQuotationPDF = async (
  banquet: Banquet,
  quoteData: QuoteData,
  selectedImages: string[]
) => {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  
  // Colors matching our theme
  const primaryColor = '#B8860B'; // Gold color from our design
  const textColor = '#2D2D2D';
  const lightGray = '#F5F5F5';

  // Header
  pdf.setFillColor(primaryColor);
  pdf.rect(0, 0, pageWidth, 30, 'F');
  
  pdf.setTextColor('#FFFFFF');
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  pdf.text('BANQUET QUOTATION', pageWidth / 2, 20, { align: 'center' });

  // Company name
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.text('Banquet Quotation Maker', pageWidth - 20, 40, { align: 'right' });

  let yPosition = 60;

  // Venue Information
  pdf.setTextColor(textColor);
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Venue Details', 20, yPosition);
  
  yPosition += 10;
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Venue: ${banquet.name}`, 20, yPosition);
  yPosition += 7;
  pdf.text(`Location: ${banquet.city}`, 20, yPosition);
  yPosition += 7;
  pdf.text(`Capacity: Up to ${banquet.capacity} guests`, 20, yPosition);
  
  yPosition += 20;

  // Client Information
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Client Information', 20, yPosition);
  
  yPosition += 10;
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Client Name: ${quoteData.clientName}`, 20, yPosition);
  yPosition += 7;
  pdf.text(`Event Date: ${new Date(quoteData.eventDate).toLocaleDateString('en-IN')}`, 20, yPosition);
  yPosition += 7;
  pdf.text(`Guests: ${quoteData.guests}`, 20, yPosition);
  yPosition += 7;
  pdf.text(`Rooms: ${quoteData.rooms}`, 20, yPosition);
  
  if (quoteData.notes) {
    yPosition += 7;
    pdf.text(`Notes: ${quoteData.notes}`, 20, yPosition);
  }

  yPosition += 20;

  // Pricing Details
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Pricing Details', 20, yPosition);
  
  yPosition += 15;
  
  // Table header
  pdf.setFillColor(lightGray);
  pdf.rect(20, yPosition - 5, pageWidth - 40, 10, 'F');
  
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Description', 25, yPosition);
  pdf.text('Quantity', 100, yPosition);
  pdf.text('Rate', 130, yPosition);
  pdf.text('Amount', 160, yPosition);
  
  yPosition += 15;
  
  // Table content
  pdf.setFont('helvetica', 'normal');
  const total = quoteData.pricePerPlate * quoteData.guests;
  
  pdf.text('Banquet per plate', 25, yPosition);
  pdf.text(quoteData.guests.toString(), 100, yPosition);
  pdf.text(`Rs ${quoteData.pricePerPlate}`, 130, yPosition);
  pdf.text(`Rs ${total.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',')}`, 160, yPosition);
  
  yPosition += 15;
  
  // Total
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(14);
  pdf.text('Total Amount:', 120, yPosition);
  pdf.text(`Rs ${total.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',')}`, 170, yPosition);

  // Images section if any images are selected
  if (selectedImages.length > 0) {
    yPosition += 30;
    
    if (yPosition > pageHeight - 60) {
      pdf.addPage();
      yPosition = 30;
    }
    
    pdf.setFontSize(16);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Gallery', 20, yPosition);
    
    yPosition += 15;
    
    // Add placeholder for images (since we can't easily embed external URLs)
    const imageWidth = 40;
    const imageHeight = 30;
    const imagesPerRow = 2;
    
    selectedImages.slice(0, 4).forEach((_, index) => {
      const col = index % imagesPerRow;
      const row = Math.floor(index / imagesPerRow);
      
      const x = 20 + col * (imageWidth + 10);
      const y = yPosition + row * (imageHeight + 10);
      
      // Draw placeholder rectangle for image
      pdf.setFillColor(lightGray);
      pdf.rect(x, y, imageWidth, imageHeight, 'F');
      pdf.setTextColor('#999999');
      pdf.setFontSize(10);
      pdf.text(`Image ${index + 1}`, x + imageWidth / 2, y + imageHeight / 2, { align: 'center' });
    });
  }

  // Footer
  const footerY = pageHeight - 20;
  pdf.setTextColor('#666666');
  pdf.setFontSize(10);
  pdf.text('Generated by Banquet Quotation Maker', pageWidth / 2, footerY, { align: 'center' });
  pdf.text(`Generated on: ${new Date().toLocaleDateString('en-IN')}`, pageWidth / 2, footerY + 5, { align: 'center' });

  // Save the PDF
  const fileName = `${banquet.name.replace(/[^a-z0-9]/gi, '_')}_quotation_${Date.now()}.pdf`;
  pdf.save(fileName);
};